// <auto-generated />
using LolApi.SummDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LolApi.Migrations
{
    [DbContext(typeof(SummonerContext))]
    [Migration("20230111155943_tftsummoner table")]
    partial class tftsummonertable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LolApi.Database.Models.TftSummonerEntry", b =>
                {
                    b.Property<int>("TftSummonerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TftSummonerId"), 1L, 1);

                    b.Property<int>("NumOfTimesSearched")
                        .HasColumnType("int");

                    b.Property<string>("SummonerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TftSummonerId");

                    b.ToTable("TftSummoner");
                });

            modelBuilder.Entity("LolApi.Models.SummonerEntry", b =>
                {
                    b.Property<int>("SummonerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SummonerId"), 1L, 1);

                    b.Property<int>("NumOfTimesSearched")
                        .HasColumnType("int");

                    b.Property<string>("SummonerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SummonerId");

                    b.ToTable("Summoner");
                });
#pragma warning restore 612, 618
        }
    }
}
