// <auto-generated />
using LolApi.SummDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LolApi.Migrations
{
    [DbContext(typeof(SummonerContext))]
    partial class SummonerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LolApi.Models.SummonerEntry", b =>
                {
                    b.Property<int>("SummonerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SummonerId"));

                    b.Property<int>("NumOfTimesSearched")
                        .HasColumnType("int");

                    b.Property<string>("SummonerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SummonerId");

                    b.ToTable("Summoner");
                });
#pragma warning restore 612, 618
        }
    }
}
